baseurl = "https://amandamata.github.io"
theme = "anubis2"
defaultContentLanguage = 'en'

[languages]
  [languages.pt-pt]
    contentDir = "content/pt"
    title = 'amandabytes'
    languageName = "pt-br"
    weight = 1

    [[languages.pt-pt.menu.main]]
    name = "início"
    pageRef = "/"
    weight = 1

    [[languages.pt-pt.menu.main]]
    name = "tags"
    url = "/tags"
    weight = 2

    [[languages.pt-pt.menu.main]]
    name = "arquivos"
    url = "/post"
    weight = 3

    [[languages.pt-pt.menu.main]]
    name = "sobre"
    url = "/about"
    weight = 4

  [languages.en]
    contentDir = "content/en"
    title = 'amandabytes'
    languageName = "en"
    weight = 1

    [[languages.en.menu.main]]
    name = "home"
    pageRef = "/"
    weight = 1

    [[languages.en.menu.main]]
    name = "tags"
    url = "/tags"
    weight = 2

    [[languages.en.menu.main]]
    name = "archive"
    url = "/post"
    weight = 3

    [[languages.en.menu.main]]
    name = "about"
    url = "/about"
    weight = 4


[params]
readMore = false # true | false; Showing readmore link in the list of posts; default: false
readNextPosts = 4 # Number of posts to show in the "Read Next" section; default: 3
colorTheme = "auto" # "auto" | "light" | "dark"; default: "auto"
colorThemeSwitcher = true # true | false; Showing color theme switcher in top of the site; default: false
toc = false # true | false; Showing table of contents in the post; default: true
math = false # true | false; Enable MathJax; default: false; You can enable MathJax in the post by adding math: true in a post's metadata section.

social = [
    { id="github", name="amandamata" },
    { id="linkedin", url="https://www.linkedin.com/in/amanda-mata/" },
]


[taxonomies]
tag = "tags" # This allows you to use the "tags" in your markdown metadata

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'base16-snazzy'