baseurl = "https://amandamata.github.io"
title = "amandamata"
theme = "minimal-bootstrap"
defaultContentLanguage = 'en'

[languages]
  [languages.pt-pt]
    contentDir = "content/pt"
    title = 'amandamata'
    languageName = "pt"
    weight = 1
  [languages.en]
    title = 'amandamata'
    contentDir = "content/en"
    weight = 1
    languageName = "en"

[[languages.en.menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1

[[languages.en.menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2

[[languages.en.menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3

[[languages.pt-pt.menu.nav]]
  name = "Posts"
  url = "/pt-pt/"
  weight = 1

[[languages.pt-pt.menu.nav]]
  name = "Tags"
  url = "/pt-pt/tags/"
  weight = 2

[[languages.pt-pt.menu.nav]]
  name = "Sobre"
  url = "/pt-pt/about/"
  weight = 3

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  description = "amandamata"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "800px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  cookieConsent = true
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
