baseurl = "https://amandamata.github.io"
title = "amandamata"
theme = "anubis2"
defaultContentLanguage = 'en'

[languages]
  [languages.pt-pt]
    contentDir = "content/pt"
    title = 'amandamata'
    languageName = "pt"
    weight = 1
  [languages.en]
    title = 'amandamata'
    contentDir = "content/en"
    weight = 1
    languageName = "en"

[author]
name = "amanda"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'base16-snazzy'